// Questions
var q = [
	'What do you understand that others don&#39;t?',
	'Why will you succeed?',
	'How big an opportunity is there?',
	'What problems/hurdles are you anticipating?',
	'Who would use your product?',
	'How much does customer acquisition cost?',
	'How will you make money?',
	'How much money could you make per year?',
	'How many users do you have?',
	'What is your user growth rate?',
	'How many users are paying?',
	'How are you meeting customers?',
	'How are you understanding customer needs?',
	'How will you get users?',
	'Who would you hire or how would you add to your team?',

	'So what are you working on?',
	'Do you have a demo?',
	'Where is the rocket science here?',
	'How does your product work in more detail?',
	'How is your product different?',
	'What are you going to do next?',
	'What&#39;s new about what you make?',
	'What, exactly, makes you different from existing options?',
	'Who needs what you&#39;re making?',
	'How do you know customers need what you&#39;re making?',
	'Why isn&#39;t someone already doing this?',
	'What obstacles will you face and how will you overcome them?',
	'How will customers and/or users find out about you?',
	'What resistance will they have to trying you and how will you overcome it?',
	'What are the key things about your field that outsiders don&#39;t understand?',
	'What part of your project are you going to build first?',
	'Who is going to be your first paying customer?',
	'If your startup succeeds, what additional areas might you be able to expand into?',
	'Why did you choose this idea?',
	'What have you learned so far from working on your product?',
	'Six months from now, what&#39;s going to be your biggest problem?',
	'Where do new users come from?',
	'What is your growth like?',
	'What&#39;s the conversion rate?',
	'What makes new users try you?',
	'Why do the reluctant users hold back?',
	'What are the top things users want?',
	'What has surprised you about user behaviour?',
	'What&#39;s an impressive thing you have done?',
	'What do you understand about your users?',
	'Why did you pick this idea to work on?',
	'What domain expertise do you have?',
	'Who are your competitors?',
	'Who might become competitors?',
	'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	'What competition do you fear most?',
	'What is your distribution strategy?',
	'How did your team meet?',
	'Why did your team get together?',
	'Who in your team does what?',
	'Who is &quot;the boss&quot;?',
	'What will you do if we don&#39;t fund you?',
	'Would you relocate to Silicon Valley?',
	'How do we know your team will stick together?',
	'What else have you created together?',
	'Are you open to changing your idea? ',
	'What systems have you hacked?',
	'Tell us about a tough problem you solved?',
	'In what ways are you resourceful?',
	'Will you reincorporate as a US company?',
	'Will your team stick at this?',
	'Tell us something surprising you have done?',
	'What&#39;s the funniest thing that has happened to you?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s the biggest mistake you have made?',
	'What is your burn rate?',
	'How long can you go before funding?',
	'What is the next step with the product evolution?',
	'Have you raised funding?',
	'Who would be your next hire?',
	
	'How do you know people want this?',
	'What do you know about this space/product others don&#39;t know?',

	'What is your long-term vision for the company?',
	'How do you plan to scale your operations?',
	'What are the biggest risks to your business?',
	'How do you handle competition from big players?',
	'What’s your exit strategy?',

	'What do you believe that most people disagree with you on?',
	'What’s your moat?',
	'What do you do better than anyone else in the world?',
	'How do you plan to acquire customers at scale?',
	'What are the metrics you track most closely?',
	'How do you plan to retain users?',
	'What is the biggest challenge you are currently facing?',
	'How do you plan to expand your market?',
	'What are the biggest threats to your success?',
	'What would make your startup fail?',
	'How do you plan to evolve the product over the next year?',
	'What are the underlying trends that make now the right time for your startup?',

	'How do you define success for your startup?',
	'What would you do if your initial idea doesn’t work?',
	'How will your team handle disagreements?',
	'What keeps you up at night about this business?',
	'What’s your biggest weakness as a team?',
	'How will you create a culture in your company?',
	'What’s the hardest decision you’ve had to make so far?',
	'What’s your plan if you don’t get funded?',
	'How will you manage growth?',
	'What’s your approach to competition?',
	'How do you handle feedback from users?',
	'What’s the most important lesson you’ve learned from your customers?',
	'How will you protect your intellectual property?',
	'What are your plans for international expansion?',
	'How do you plan to build brand loyalty?',
	'What’s your plan for onboarding new users?',
	'How will you measure product-market fit?',
	'What’s your long-term vision for the company culture?',
	'What’s your plan for scaling your infrastructure?',
	'How will you manage operational costs as you grow?',

	'What’s the biggest risk to your business model?',
	'How will you differentiate your product as the market evolves?',
	'What’s your exit strategy?',
	'How do you plan to maintain quality as you scale?',
	'What’s your strategy for building partnerships?',
	'How do you ensure customer satisfaction?',
	'What’s your plan for dealing with regulatory challenges?',
	'How do you handle negative feedback or criticism?',
	'What are the key milestones for the next six months?',
	'How do you plan to manage your team as it grows?',
	'What’s your approach to setting and tracking goals?',
	'How do you stay ahead of industry trends?',
	'What’s your backup plan if your primary strategy fails?',
	'How will you maintain a competitive edge?',
	'What’s your strategy for customer support?',
	'How do you plan to engage with your user community?',
	'What motivates your team?',
	'How do you plan to scale your marketing efforts?',
	'What’s your strategy for hiring top talent?',
	'How will you maintain your company’s core values as you grow?',
	'What are typical templates?',
	'I\'m not sure what is the problem?',
	'What is your burn rate?',
	'How long can you go before funding?',
	'Have you raised funding?',
	'What will you do if we don’t fund you?',
	'Would you relocate to Silicon Valley during YC?',
	'Who is "the boss?"',
	'What role will each founder have?',
	'How do we know your team will stick together?',
	'Will your team stick at this?',
	'What else have you created together?',
	'Are you open to changing your idea?',
	'Tell us anything that went bad recently',
	'Tell us about a tough problem you solved?',
	'In what ways are you resourceful?',
	'What’s the worst thing that has happened? What’s the biggest mistake you have made?',
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];